/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

const envProjectId = (import.meta as any)?.env?.VITE_SUPABASE_PROJECT_ID as string | undefined;
const envAnonKey = (import.meta as any)?.env?.VITE_SUPABASE_ANON_KEY as string | undefined;

export const projectId = envProjectId || "wocchwrvlhqdwtvfwfab"
export const publicAnonKey = envAnonKey || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndvY2Nod3J2bGhxZHd0dmZ3ZmFiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU0ODQ1ODIsImV4cCI6MjA5MTA2MDU4Mn0.BVlVGSpKth0t6kFSAoZSU0N_DzAYpWGAMIn4RhxRswk"
